---
title: "PRUEBA1"
author: "VICTOR TERRON"
date: "17/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(engine.path = list(octave="C:/Program Files/GNU Octave/Octave-6.1.0/mingw64/bin/octave-cli-6.1.0.exe") )
```

ESTE DOCUMENTO ES UN EJEMPLO DE R & PHYTHON CON LIBRERÍA RETICULATE
## LIBRERÍA RETICULATE
RETICULATE ES UNA INTERFACE DE PYTHON
```{r}
library(reticulate)
use_python("C:/ProgramData/Anaconda3/python3")
py_install("numpy")
py_install("pandas")
py_install("scipy")
scipy <- import("scipy")
numpy <- import("numpy")
os  <- import ("os")
os$listdir(".")
```
##OPERACIONES
```{r}
np <- import("numpy",convert = FALSE)
x<-np$array(c(1:4))
sum<-x$cumsum()
print(sum)
py_to_r(sum)
```
##AYUDA
```{r}
help(py_to_r)
py_help(os$chdir)
```
##ARRAYS
```{r}
a <- np_array(c(1:10), order="C")
a
```
##IRIS
```{r}
datos <- iris
head(datos)
datos_py <- r_to_py(datos)
```
```{python}
import numpy as np
import pandas as pd
r.datos_py.head()
```
##SPARCE MATRIX
```{r}
library(Matrix)
N <- 6
sparse_mat <- sparseMatrix(
  i = sample(N, N, replace=F),
  j = sample(N, N, replace=F),
  x = runif(N),
  dims=c(N,N)
)
sparse_mat
sparce_mat_py <- r_to_py(sparse_mat)
```



